<?php

/**
 * @file
 * Contains the controller classes.
 */

/**
 * Controller class for the t9n_mgmt_translator entity.
 */
class TranslationManagementTranslatorController extends EntityAPIControllerExportable {

}

/**
 * Controller class for the t9n_mgmt_job entity.
 */
class TranslationManagementJobController extends EntityAPIController {

}

/**
 * Controller class for the t9n_mgmt_map entity.
 */
class TranslationManagementMapController extends EntityAPIController {

}