<?php

/*
 * @file
 * Entity classes for Translation Management entities.
 */

/**
 * Entity class for the t9n_mgmt_translator entity.
 */
class TranslationManagementTranslator extends Entity {

}

/**
 * Entity class for the t9n_mgmt_job entity.
 */
class TranslationManagementJob extends Entity {

}

/**
 * Entity class for the t9n_mgmt_map entity.
 */
class TranslationManagementMap extends Entity {

}
