<?php

/**
 * @file
 * Main module file for the Translation Management module.
 */

use Drupal\Component\Utility\NestedArray;
use Drupal\Component\Utility\Unicode;
use Drupal\tmgmt\Entity\Job;
use Drupal\tmgmt\Entity\Translator;

/**
 * @addtogroup tmgmt_job
 * @{
 */
/**
 * A new translation job.
 *
 * In the default user interface, jobs with this state are so called cart jobs.
 * Each user gets his cart jobs listed in a block and can check them out.
 */
define('TMGMT_JOB_STATE_UNPROCESSED', 0);

/**
 * A translation job that has been submitted to the translator.
 *
 * Translator plugins are responsible for setting this state in their
 * implementation of
 * TranslatorPluginControllerInterface::requestTranslation().
 */
define('TMGMT_JOB_STATE_ACTIVE', 1);

/**
 * A translation job that has been rejected by the translator.
 *
 * The translator plugin can use this state if the job has been actively
 * rejected. However, this should be avoided by doing the necessary checks
 * in the canTranslate() method and in the job configuration settings.
 *
 * A rejected job can be re-submitted.
 */
define('TMGMT_JOB_STATE_REJECTED', 2);

/**
 * The translation has been accepted and the job is finished.
 *
 * Once the job has been accepted, the source plugins are called to update their
 * sources with the translated data.
 */
define('TMGMT_JOB_STATE_ACCEPTED', 3);

/**
 * The translation job has been aborted.
 *
 * A job can be aborted at any time. If he is currently in the submitted state
 * the translator plugin is asked if this translation can be aborted and needs
 * to confirm it by returning TRUE in abortTranslation().
 */
define('TMGMT_JOB_STATE_ABORTED', 4);

/**
 * The translation job has been finished.
 *
 * A job is marked as 'finished' after every single attached job item has been
 * reviewed, accepted and saved.
 */
define('TMGMT_JOB_STATE_FINISHED', 5);

/**
 * The translation job item is active and waiting to be translated.
 *
 * A job item is marked as 'active' until every translatable piece of text in
 * the job item has been translated and cached on the job item entity.
 */
define('TMGMT_JOB_ITEM_STATE_ACTIVE', 1);

/**
 * The translation job item needs to be reviewed.
 *
 * A job item is marked as 'needs review' after every single piece of text in
 * the job item has been translated by the translation provider. After the
 * review procedure is finished the job item can be accepted and saved.
 */
define('TMGMT_JOB_ITEM_STATE_REVIEW', 2);

/**
 * The translation job item has been reviewed and accepted.
 *
 * After reviewing a job item it can be accepted by the reviewer. Once the user
 * has accepted the job item, the translated data will be propagated to the
 * source controller which will also take care of flagging the job item as
 * 'accepted' if the translated object could be saved successfully.
 */
define('TMGMT_JOB_ITEM_STATE_ACCEPTED', 3);

/**
 * The translation process of the job item is aborted.
 */
define('TMGMT_JOB_ITEM_STATE_ABORTED', 4);

/**
 * The translation data item has not been translated.
 */
define('TMGMT_DATA_ITEM_STATE_PENDING', 0);

/**
 * The translation data item has been reviewed.
 */
define('TMGMT_DATA_ITEM_STATE_REVIEWED', 1);

/**
 * The translation data item has been translated.
 */
define('TMGMT_DATA_ITEM_STATE_TRANSLATED', 2);

/**
 * The translation data item has been reviewed.
 */
define('TMGMT_DATA_ITEM_STATE_ACCEPTED', 3);

/**
 * Maximum length of a job or job item label.
 */
define('TMGMT_JOB_LABEL_MAX_LENGTH', 128);
/**
 * @} End of "addtogroup tmgmt_job".
 */

/**
 * String used to delimit flattened array keys.
 */
const TMGMT_ARRAY_DELIMITER = '][';

/**
 * Implements hook_modules_installed().
 */
function tmgmt_modules_installed($modules) {
  $translator_manager = \Drupal::service('plugin.manager.tmgmt.translator');
  $translator_manager->clearCachedDefinitions();
  foreach ($translator_manager->getDefinitions() as $definition) {
    // Check if this translator plugin has been added by one of the recently
    // installed modules and doesn't prevent auto creation.
    if ((!isset($definition['auto create']) || $definition['auto create'] == TRUE) && in_array($definition['provider'], $modules)) {
      tmgmt_translator_auto_create($definition);
    }
  }
}

/**
 * Implements hook_cron().
 */
function tmgmt_cron() {
  $offset = \Drupal::config('tmgmt.settings')->get('purge_finished');
  if ($offset != '_never') {
    // Delete all finished translation jobs that haven't been changed for a
    // time span longer than the given offset.
    $tjid = \Drupal::entityQuery('tmgmt_job')
      ->condition('state', TMGMT_JOB_STATE_FINISHED)
      ->condition('changed', REQUEST_TIME - $offset, '<=')
      ->execute();
    if (!empty($tjid)) {
      entity_delete_multiple('tmgmt_job', $tjid);
    }
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function tmgmt_local_tasks_alter(&$local_tasks) {
  // Look for the first source overview local task and make the parent use the
  // same route arguments.
  // @todo: Find a nicer way to get the main source (usually entity:node), also,
  //   this looses the trail because the parent points directly to the first
  //   sub-task. Use a different route that doesn't require the arguments?
  foreach ($local_tasks as $plugin_id => $local_task) {
    if (strpos($plugin_id, 'tmgmt.sources:') !== FALSE) {
      $local_tasks['tmgmt.sources_parent']['route_parameters'] = $local_task['route_parameters'];
      return;
    }
  }
}

/**
 * Returns an array of languages that are available for translation.
 *
 * @return array
 *   An array of languages in ISO format.
 */
function tmgmt_available_languages($exclude = array()) {
  $languages = language_list();
  // Remove the language in $exclude from the list of available languages and
  // then apply a filter that only leaves the supported target languages on
  // the list.
  $labels = array();
  foreach ($languages as $langcode => $language) {
    if (!in_array($langcode, $exclude)) {
      $labels[$langcode] = $language->getName();
    }
  }
  return $labels;
}

/**
 * @addtogroup tmgmt_job
 * @{
 */
/**
 * Loads a translation job.
 *
 * @param int $tjid
 *   Translation job id.
 *
 * @return \Drupal\tmgmt\Entity\Job
 *   Loaded translation job entity.
 */
function tmgmt_job_load($tjid) {
  return entity_load('tmgmt_job', $tjid);
}

/**
 * Loads translation jobs.
 */
function tmgmt_job_load_multiple(array $tjids = array(), $conditions = array()) {
  return entity_load_multiple('tmgmt_job', $tjids, $conditions);
}

/**
 * Loads active job entities that have a job item with the identifiers.
 *
 * @param $plugin
 *   The source plugin.
 * @param $item_type
 *   The source item type.
 * @param $item_id
 *   The source item id.
 * @param string $source_language
 *   The source language of the item.
 *
 * @return array
 *   An array of job entities.
 */
function tmgmt_job_item_load_latest($plugin, $item_type, $item_id, $source_language) {
  $query = db_select('tmgmt_job_item', 'tji');
  $query->innerJoin('tmgmt_job', 'tj', 'tj.tjid = tji.tjid');
  $result = $query->condition('tj.source_language', $source_language)
    // Only query for jobs that are currently active.
    ->condition('tj.state', array(TMGMT_JOB_STATE_UNPROCESSED, TMGMT_JOB_STATE_ACTIVE))
    // And only query for job items that are not yet finished.
    ->condition('tji.state', TMGMT_JOB_ITEM_STATE_ACCEPTED, '<>')
    ->condition('tji.plugin', $plugin)
    ->condition('tji.item_type', $item_type)
    ->condition('tji.item_id', $item_id)
    ->fields('tji', array('tjiid'))
    ->fields('tj', array('target_language'))
    ->orderBy('tji.changed', 'DESC')
    ->groupBy('tj.target_language')
    ->groupBy('tji.tjiid')
    ->groupBy('tji.changed')
    ->execute();
  if ($items = $result->fetchAllKeyed()) {
    $return = array();
    foreach (tmgmt_job_item_load_multiple(array_keys($items)) as $key => $item) {
      $return[$items[$key]] = $item;
    }
    return $return;
  }
  return FALSE;
}

/**
 * Loads all latest job entities that have a job item with the identifiers.
 *
 * @param $plugin
 *   The source plugin.
 * @param $item_type
 *   The source item type.
 * @param $item_id
 *   The source item id.
 * @param string $source_language
 *   The source language of the item.
 *
 * @return array
 *   An array of job entities.
 */
function tmgmt_job_item_load_all_latest($plugin, $item_type, $item_id, $source_language) {
  $query = db_select('tmgmt_job_item', 'tji');
  $query->innerJoin('tmgmt_job', 'tj', 'tj.tjid = tji.tjid');
  $result = $query->condition('tj.source_language', $source_language)
    ->condition('tji.state', TMGMT_JOB_ITEM_STATE_ACCEPTED, '<>')
    ->condition('tji.plugin', $plugin)
    ->condition('tji.item_type', $item_type)
    ->condition('tji.item_id', $item_id)
    ->fields('tji', array('tjiid'))
    ->fields('tj', array('target_language'))
    ->orderBy('tji.changed', 'DESC')
    ->groupBy('tj.target_language')
    ->groupBy('tji.tjiid')
    ->execute();
  if ($items = $result->fetchAllKeyed()) {
    $return = array();
    foreach (tmgmt_job_item_load_multiple(array_keys($items)) as $key => $item) {
      $return[$items[$key]] = $item;
    }
    return $return;
  }
  return FALSE;
}

/**
 * Returns a job which matches the requested source- and target language by
 * user. If no job exists, a new job object will be created.
 *
 * @param $source_language
 *   The source language from which should be translated.
 * @param $target_language
 *   The target language into which should be translated.
 * @param $account
 *   (Optional) A user object. Defaults to the currently logged in user.
 *
 * @return \Drupal\tmgmt\Entity\Job
 *   The job entity.
 */
function tmgmt_job_match_item($source_language, $target_language, $account = NULL) {
  $account = isset($account) ? $account : \Drupal::currentUser();
  $tjid = \Drupal::entityQuery('tmgmt_job')
    ->condition('source_language', $source_language)
    ->condition('target_language', $target_language)
    ->condition('uid', $account->id())
    ->condition('state', TMGMT_JOB_STATE_UNPROCESSED)
    ->execute();
  if (!empty($tjid)) {
    return tmgmt_job_load(reset($tjid));
  }
  return tmgmt_job_create($source_language, $target_language, $account->id());
}

/**
 * Checks whether a job is finished by querying the job item table for
 * unfinished job items.
 *
 * @param $tjid
 *   The identifier of the job.
 * @return bool
 *   TRUE if the job is finished, FALSE otherwise.
 */
function tmgmt_job_check_finished($tjid) {
  return !\Drupal::entityQuery('tmgmt_job_item')
    ->condition('tjid', $tjid)
    ->condition('state', TMGMT_JOB_ITEM_STATE_ACCEPTED, '<>')
    ->range(0, 1)
    ->count()
    ->execute();
}

/**
 * Creates a translation job.
 *
 * @param $source_language
 *   The source language from which should be translated.
 * @param $target_language
 *   The target language into which should be translated.
 * @param $values
 *   (Optional) An array of additional entity values.
 *
 * @return \Drupal\tmgmt\Entity\Job
 *   The job entity.
 */
function tmgmt_job_create($source_language, $target_language, $uid = 0, array $values = array()) {
  return entity_create('tmgmt_job', array_merge($values, array(
    'source_language' => $source_language,
    'target_language' => $target_language,
    'uid' => $uid,
  )));
}

/**
 * Loads an array with the word and status statistics of a job.
 *
 * @param $tjids
 *   An array of job ids.
 *
 * @return
 *   An array of objects with the keys word_count, count_pending,
 *   count_accepted, count_reviewed and count_translated.
 */
function tmgmt_job_statistics_load(array $tjids) {
  $statistics = &drupal_static(__FUNCTION__, array());

  // First try to get the values from the cache.
  $return = array();
  $tjids_to_load = array();
  foreach ($tjids as $tjid) {
    if (isset($statistics[$tjid])) {
      // Info exists in cache, get it from there.
      $return[$tjid] = $statistics[$tjid];
    }
    else {
      // Info doesn't exist in cache, add job to the list that needs to be
      // fetched.
      $tjids_to_load[] = $tjid;
    }
  }

  // If there are remaining jobs, build a query to fetch them.
  if (!empty($tjids_to_load)) {
    // Build the query to fetch the statistics.
    $query = db_select('tmgmt_job_item', 'tji')
      ->fields('tji', array('tjid'));
    $query->addExpression('SUM(word_count)', 'word_count');
    $query->addExpression('SUM(count_accepted)', 'count_accepted');
    $query->addExpression('SUM(count_reviewed)', 'count_reviewed');
    $query->addExpression('SUM(count_pending)', 'count_pending');
    $query->addExpression('SUM(count_translated)', 'count_translated');
    $result = $query->groupBy('tjid')
      ->condition('tjid', $tjids_to_load)
      ->execute();

    foreach ($result as $row) {
      $return[$row->tjid] = $statistics[$row->tjid] = $row;
    }
  }
  return $return;
}

/**
 * Returns a specific statistic of a job.
 *
 * @param $job
 *   The translation job entity.
 * @param $key
 *   One of word_count, count_pending, count_accepted, count_reviewed and
 *   count_translated.
 *
 * @return
 *   The requested information as an integer.
 */
function tmgmt_job_statistic(Job $job, $key) {
  $statistics = tmgmt_job_statistics_load(array($job->id()));
  if (isset($statistics[$job->id()]->$key)) {
    return $statistics[$job->id()]->$key;
  }
  return 0;
}

/**
 * Static method to retrieve a labeled list of all available states.
 *
 * @return array
 *   A list of all available states.
 */
function tmgmt_job_states() {
  return array(
    TMGMT_JOB_STATE_UNPROCESSED => t('Unprocessed'),
    TMGMT_JOB_STATE_ACTIVE => t('Active'),
    TMGMT_JOB_STATE_REJECTED => t('Rejected'),
    TMGMT_JOB_STATE_ABORTED => t('Aborted'),
    TMGMT_JOB_STATE_FINISHED => t('Finished'),
  );
}

/**
 * Static method to retrieve a labeled list of all available states.
 *
 * @return array
 *   A list of all available states.
 */
function tmgmt_job_item_states() {
  return array(
    TMGMT_JOB_ITEM_STATE_ACTIVE => t('In progress'),
    TMGMT_JOB_ITEM_STATE_REVIEW => t('Needs review'),
    TMGMT_JOB_ITEM_STATE_ACCEPTED => t('Accepted'),
    TMGMT_JOB_ITEM_STATE_ABORTED => t('Aborted'),
  );
}

/**
 * Loads a translation job item.
 *
 * @param $tjiid
 *   A job item id.
 *
 * @return \Drupal\tmgmt\Entity\JobItem
 *   The loaded job item or FALSE if the query returned no results.
 */
function tmgmt_job_item_load($tjiid) {
  return entity_load('tmgmt_job_item', $tjiid);
}

/**
 * Loads translation job items.
 *
 * @param $tjiids
 *   An array of job item ids.
 * @param $conditions
 *   An array of additional conditions.
 *
 * @return \Drupal\tmgmt\Entity\JobItem[]
 *   An array of job item entities or an empty array if the query returned no
 *   results.
 */
function tmgmt_job_item_load_multiple($tjiids = array(), $conditions = array()) {
  return entity_load_multiple('tmgmt_job_item', $tjiids, $conditions);
}

/**
 * Creates a translation job item.
 *
 * @param $plugin
 *   The plugin name.
 * @param $item_type
 *   The source item type.
 * @param $item_id
 *   The source item id.
 * @param $values
 *   (Optional) An array of additional entity values to be set.
 *
 * @return \Drupal\tmgmt\Entity\JobItem
 *   The created, not yet saved, job item entity.
 */
function tmgmt_job_item_create($plugin, $item_type, $item_id, array $values = array()) {
  return entity_create('tmgmt_job_item', array_merge($values, array(
    'plugin' => $plugin,
    'item_type' => $item_type,
    'item_id' => $item_id,
  )));
}

/**
 * Loads a translation job message.
 *
 * @param $mid
 *   A job message id.
 *
 * @return TMGMTMessage
 *   A job message entity or FALSE if the query didn't yield any results.
 */
function tmgmt_message_load($mid) {
  // Avoid collision with the message module because this looks like the module
  // implements hook_ENTITY_TYPE_load() for message.
  if (!is_array($mid)) {
    return entity_load('tmgmt_message', $mid);
  }
}

/**
 * Loads translation job messages.
 */
function tmgmt_message_load_multiple($mids = array()) {
  return entity_load_multiple('tmgmt_message', $mids);
}

/**
 * Creates a translation job message.
 *
 * @param $message
 *   (Optional) The message to be saved.
 * @param $variables
 *   (Optional) An array of variables to replace in the message on display.
 * @param $values
 *   (Optional) An array of additional entity values to be set.
 *
 * @return \Drupal\tmgmt\Entity\JobItem
 *   The created, not yet saved, job item entity.
 */
function tmgmt_message_create($message = '', $variables = array(), $values = array()) {
  return entity_create('tmgmt_message', array_merge($values, array(
    'message' => $message,
    'variables' => $variables,
    'uid' => \Drupal::currentUser()->id(),
  )));
}
/**
 * @} End of "addtogroup tmgmt_job".
 */
/**
 * @addtogroup tmgmt_translator
 * @{
 */

/**
 * Loads a translator based on the name.
 *
 * @param $name
 *   The machine-readable name of the translator entity to load.
 *
 * @return \Drupal\tmgmt\Entity\Translator
 *   A translator entity.
 */
function tmgmt_translator_load($name) {
  return entity_load('tmgmt_translator', $name);
}

/**
 * Loads multiple translators based on their name.
 *
 * @param $names
 *   (Optional) An array of machine-readable names of the translator entities to
 *   load or FALSE to load all available translator entities.
 *
 * @return array
 *   An array of translators with the machine-readable name of the translators
 *   as array keys.
 */
function tmgmt_translator_load_multiple($names = NULL) {
  return entity_load_multiple('tmgmt_translator', $names);
}

/**
 * Loads all translators that are available and, if a translation job is given,
 * support translations for that job with its current configuration.
 *
 * @param \Drupal\tmgmt\Entity\Job $job
 *   (Optional) A translation job.
 *
 * @return array
 *   An array of translators with the machine-readable name of the translators
 *   as array keys.
 */
function tmgmt_translator_load_available($job) {
  $translators = tmgmt_translator_load_multiple();
  foreach ($translators as $name => $translator) {
    if (!$translator->isAvailable() || (isset($job) && !$translator->canTranslate($job))) {
      unset($translators[$name]);
    }
  }
  return $translators;
}

/**
 * Checks whether a translator with a certain name is busy and therefore can't
 * be modified or deleted. A translator is considered 'busy' if there are jobs
 * attached to it that are in an active state.
 *
 * @param $translator
 *   The machine-readable name of a translator.
 *
 * @return boolean
 *   TRUE if the translator is busy, FALSE otherwise.
 */
function tmgmt_translator_busy($translator) {
  return (bool) \Drupal::entityQuery('tmgmt_job')
    ->condition('state', TMGMT_JOB_STATE_ACTIVE)
    ->condition('translator', $translator)
    ->range(0, 1)
    ->count()
    ->execute();
}

/**
 * Creates a translator entity.
 *
 * @param $plugin
 *   The plugin of the translator.
 * @param $name
 *   The machine-readable name of the translator.
 * @param $label
 *   The label of the translator.
 * @param $description
 *   (Optional) The description of the translator. Defaults to an empty string.
 * @param $settings
 *   (Optional) An array of settings for the translator.
 * @param $values
 *   (Optional) Array of additional entity values.
 *
 * @return Translator
 *   The created, not yet saved, translator entity.
 */
function tmgmt_translator_create($plugin, $name, $label, $description = '', $settings = array(), $values = array()) {
  return entity_create('tmgmt_translator', array_merge($values, array(
    'plugin' => $plugin,
    'name' => $name,
    'label' => $label,
    'description' => $description,
    'settings' => $settings,
  )));
}

/**
 * Auto creates a translator from a translator plugin definition.
 *
 * @param array $definition
 *   The definition of a translator plugin.
 */
function tmgmt_translator_auto_create(array $definition) {
  $plugin = $definition['id'];
  if (!tmgmt_translator_load($plugin)) {
    $label = $definition['label'] . ' (auto created)';
    $translator = tmgmt_translator_create($plugin, $plugin, $label, (string) $definition['description']);
    // Append some default settings from the translator plugin definition.
    $translator->setSettings($translator->getController()->defaultSettings());
    $translator->save();
  }
}

/**
 * Returns a list of all available translator labels.
 *
 * @return array
 *   An array containing all available translator labels.
 */
function tmgmt_translator_labels() {
  $labels = array();
  foreach (tmgmt_translator_load_multiple() as $translator) {
    $labels[$translator->id()] = $translator->label();
  }
  return $labels;
}

/**
 * Returns a list of flagged translator labels. If a translator is not available
 * it will be suffixed with a short text explaining why it is not available.
 * This can either be because the configuration of the passed job is not
 * supported or because the translator service can't be reached.
 *
 * @param \Drupal\tmgmt\Entity\Job $job
 *   (Optional) A translation job.
 *
 * @return array
 *   An array of flagged translator labels.
 */
function tmgmt_translator_labels_flagged($job = NULL) {
  $labels = array();
  foreach (tmgmt_translator_load_multiple() as $translator) {
    if (!$translator->isAvailable()) {
      $labels[$translator->id()] = t('@label (not available)', array('@label' => $translator->label()));
    }
    elseif (isset($job) && !$translator->canTranslate($job)) {
      $labels[$translator->id()] = t('@label (unsupported)', array('@label' => $translator->label()));
    }
    else {
      $labels[$translator->id()] = $translator->label();
    }
  }
  return $labels;
}

/**
 * Determines if the translator plugin supports remote language mappings.
 *
 * @param \Drupal\tmgmt\Entity\Translator $translator
 *   Translator entity.
 *
 * @return bool
 *   In case translator does not explicitly state that it does not provide the
 *   mapping feature it will return TRUE.
 */
function tmgmt_provide_remote_languages_mappings(Translator $translator) {
  $definition = \Drupal::service('plugin.manager.tmgmt.translator')->getDefinition($translator->getPluginId());

  if (!isset($definition['map_remote_languages'])) {
    return TRUE;
  }

  return $definition['map_remote_languages'];
}

/**
 * Determines if job settings of the translator will be handled by its plugin.
 *
 * @param \Drupal\tmgmt\Entity\Translator $translator
 *   Translator entity.
 *
 * @return bool
 *   If job settings are to be handled by the plugin.
 */
function tmgmt_job_settings_custom_handling(Translator $translator) {
  $definition = \Drupal::service('plugin.manager.tmgmt.translator')->getDefinition($translator->getPluginId());

  if (isset($definition['job_settings_custom_handling'])) {
    return $definition['job_settings_custom_handling'];
  }

  return FALSE;
}
/**
 * @} End of "addtogroup tmgmt_translator".
 */
/**
 * @addtogroup tmgmt_source
 * @{
 */

/**
 * Returns an array of translatable item types of a source plugin.
 *
 * @param $plugin
 *   The machine-readable name of a source plugin.
 *
 * @return array
 *   The array of translatable item types.
 *
 * @see TMGMTSourcePluginControllerInterface::getItemTypes()
 */
function tmgmt_source_translatable_item_types($plugin) {
  $instance = \Drupal::service('plugin.manager.tmgmt.source')->createInstance($plugin);
  return $instance->getItemTypes();
}

/**
 * @param $plugin
 * @param $item_type
 * @return bool
 */
function tmgmt_source_is_translatable_item_type($plugin, $item_type) {
  return array_key_exists($item_type, tmgmt_source_translatable_item_types($plugin));
}
/**
 * @} End of "addtogroup tmgmt_source".
 */

/**
 * Converts a nested data array into a flattened structure with a combined key.
 *
 * This function can be used by translators to help with the data conversion.
 *
 * Nested keys will be joined together using a colon, so for example
 * $data['key1']['key2']['key3'] will be converted into
 * $flattened_data['key1][key2][key3'].
 *
 * @param $data
 *   The nested array structure that should be flattened.
 * @param $prefix
 *   Internal use only, indicates the current key prefix when recursing into
 *   the data array.
 *
 * @return array
 *   The flattened data array.
 *
 * @see tmgmt_unflatten_data()
 */
function tmgmt_flatten_data($data, $prefix = NULL, $label = array()) {
  $flattened_data = array();
  if (isset($data['#label'])) {
    $label[] = $data['#label'];
  }
  // Each element is either a text (has #text property defined) or has children,
  // not both.
  if (!empty($data['#text'])) {
    $flattened_data[$prefix] = $data;
    $flattened_data[$prefix]['#parent_label'] = $label;
  }
  else {
    $prefix = isset($prefix) ? $prefix . TMGMT_ARRAY_DELIMITER : '';
    foreach (element_children($data) as $key) {
      $flattened_data += tmgmt_flatten_data($data[$key], $prefix . $key, $label);
    }
  }
  return $flattened_data;
}

/**
 * Converts string keys to array keys.
 *
 * There are three conventions for data keys in use. This function accepts each
 * of it an ensures a array of keys.
 *
 * @param $key
 *   The key can be either be an array containing the keys of a nested array
 *   hierarchy path or a string with '][' or '|' as delimiter.
 *
 * @return
 *   Array of keys.
 */
function tmgmt_ensure_keys_array($key) {
  if (empty($key)) {
    return array();
  }
  if (!is_array($key)) {
    if (strstr($key, '|')) {
      $key = str_replace('|', TMGMT_ARRAY_DELIMITER, $key);
    }
    $key = explode(TMGMT_ARRAY_DELIMITER, $key);
  }
  return $key;
}

/**
 * Converts keys array to string key.
 *
 * There are three conventions for data keys in use. This function accepts each
 * of it an ensures a sting keys.
 *
 * @param $key
 *   The key can be either be an array containing the keys of a nested array
 *   hierarchy path or a string.
 * @param
 *   Delimiter to be use in the keys string. Default is ']['.
 *
 * @return
 *  Keys string.
 */
function tmgmt_ensure_keys_string($key, $delimiter = TMGMT_ARRAY_DELIMITER) {
  if (is_array($key)) {
    $key = implode($delimiter, $key);
  }
  return $key;
}

/**
 * Converts a flattened data structure into a nested array.
 *
 * This function can be used by translators to help with the data conversion.
 *
 * Nested keys will be created based on the colon, so for example
 * $flattened_data['key1][key2][key3'] will be converted into
 * $data['key1']['key2']['key3'].
 *
 * @param $data
 *   The flattened data array.
 *
 * @return array
 *   The nested data array.
 *
 * @see tmgmt_flatten_data()
 */
function tmgmt_unflatten_data($flattened_data) {
  $data = array();
  foreach ($flattened_data as $key => $flattened_data_entry) {
    NestedArray::setValue($data, explode(TMGMT_ARRAY_DELIMITER, $key), $flattened_data_entry);
  }
  return $data;
}

/**
 * Array filter callback for filtering untranslatable source data elements.
 */
function _tmgmt_filter_data($value) {
  return !(empty($value['#text']) || (isset($value['#translate']) && $value['#translate'] === FALSE));
}

/**
 * Returns a label for a data item.
 *
 * @param array $data_item
 *   The data item array.
 * @param int $max_length
 *   (optional) Specify the max length that the resulting label string should
 *   be cut to.
 *
 * @return string
 *   A label for the data item.
 */
function tmgmt_data_item_label(array $data_item, $max_length = NULL) {
  if (!empty($data_item['#parent_label'])) {
    if ($max_length) {
      // When having multiple label parts, we don't know how long each of them is,
      // truncating each to the same length might result in a considerably shorter
      // length than max length when there are short and long labels. Instead,
      // start with the max length and repeat until the whole string is less than
      // max_length. Remove 4 characters per part to avoid unecessary loops.
      $current_max_length = $max_length - (count($data_item['#parent_label']) * 4);
      do {
        $current_max_length--;
        $labels = array();
        foreach ($data_item['#parent_label'] as $label_part) {
          // If this not the last part, reserve 3 characters for the delimiter.
          $labels[] = Unicode::truncate($label_part, $current_max_length, FALSE, TRUE);
        }
        $label = implode(t(' > '), $labels);
      } while (Unicode::strlen($label) > $max_length);
      return $label;
    }
    else {
      return implode(t(' > '), $data_item['#parent_label']);
    }
  }
  elseif (!empty($data_item['#label'])) {
    return $max_length ? Unicode::truncate($data_item['#label'], $max_length, FALSE, TRUE) : $data_item['#label'];
  }
  else {
    // As a last resort, fall back to a shortened version of the text. Default
    // to a limit of 50 characters.
    return Unicode::truncate($data_item['#text'], $max_length ? $max_length : 50, FALSE, TRUE);
  }
}

/**
 * Calculates number of words, which a text consists of.
 * Is placed as a separately function to be coverable by unit tests.
 * @see TMGMTWordCountUnitTestCase
 *
 * @param string $text
 * @return int
 *   Returns count of words of text.
 */
function tmgmt_word_count($text) {
  // Strip tags in case it is requested to not include them in the count.
  if (\Drupal::config('tmgmt.settings')->get('word_count_exclude_tags')) {
    $text = strip_tags($text);
  }
  // Replace each punctuation mark with space.
  $text = str_replace(array('`', '~', '!', '@', '"', '#', '$', ';', '%', '^', ':', '?', '&', '*', '(', ')', '-', '_', '+', '=', '{', '}', '[', ']', '\\', '|', '/', '\'', '<', '>', ',', '.'), ' ', $text);
  // Remove duplicate spaces.
  $text =  trim(preg_replace('/ {2,}/', ' ', $text));
  // Turn into an array.
  $array = ($text) ? explode(' ', $text) : array();
  // How many are they?
  $count = count($array);
  // That is what we need.
  return $count;
}
