<?php
/**
 * @file
 * UI.
 */

/**
 * Implements hook_permission().
 */
function tmgmt_ui_permission() {
  return array(
    'administer tmgmt' => array(
      'title' => t('administer Translation Management UI'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function tmgmt_ui_menu() {
    $items = array();

    $items['admin/tmgmt'] = array(
        'title' => 'Translation Management',
        'description' => 'Use the Translation Management',
        'page callback' => 'tmgmt_ui_content',
        'access arguments' => array('administer tmgmt'),
        'weight' => -20,
        'file' => 'tmgmt_ui.pages.inc',
    );
    $items['admin/tmgmt/my-translation-management'] = array(
        'title' => 'Overview',
        'page callback' => 'tmgmt_ui_content',
        'access arguments' => array('administer tmgmt'),
        'weight' => -20,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'file' => 'tmgmt_ui.pages.inc',
    );
    $items['admin/tmgmt/jobs'] = array(
        'title' => 'Jobs Overview',
        'page callback' => 'tmgmt_ui_jobs',
        'access arguments' => array('administer tmgmt'),
        'weight' => -19,
        'type' => MENU_LOCAL_TASK,
        'file' => 'tmgmt_ui.pages.inc',
    );
    $items['admin/tmgmt/nodes'] = array(
        'title' => 'Nodes Overview',
        'page callback' => 'tmgmt_ui_nodes',
        'access arguments' => array('administer tmgmt'),
        'weight' => -18,
        'type' => MENU_LOCAL_TASK,
        'file' => 'tmgmt_ui.pages.inc',
    );

    return $items;
}

/**
 * Implements hook_views_api().
 */
function tmgmt_ui_views_api() {
  return array('api' => 2);
}

/**
 * Implements hook_views_default_views().
 */
function tmgmt_ui_views_default_views() {
  return _tmgmt_ui_load_all_exports('tmgmt_ui', 'views', 'view.inc', 'view');
}

/**
 * Fetches an array of exportables from files.
 *
 * @param $module
 *   The module invoking this request. (Can be called by other modules.)
 * @param $directory
 *   The subdirectory in the custom module.
 * @param $extension
 *   The file extension.
 * @param $name
 *   The name of the variable found in each file. Defaults to the same as
 *   $extension.
 *
 * @return
 *   Array of $name objects.
 */
function _tmgmt_ui_load_all_exports($module, $directory, $extension, $name = NULL) {
  if (!$name) {
    $name = $extension;
  }

  $return = array();
  // Find all the files in the directory with the correct extension.
  $files = file_scan_directory(drupal_get_path('module', $module) . "/$directory", "/\.{$extension}$/");
  foreach ($files as $path => $file) {
    require $path;
    if (isset($$name)) {
      $return[$$name->name] = $$name;
    }
  }

  return $return;
}