<?php

/**
 * @file
 * Module file of the translation management test module.
 */

use Drupal\tmgmt\Plugin\Core\Entity\Job;

/**
 * Implements hook_tmgmt_translator_info_alter().
 */
function tmgmt_test_tmgmt_translator_info_alter(&$definitions) {
  $map = Drupal::state()->get('tmgmt_test_translator_map_languages');
  $definitions['test_translator']['map_remote_languages'] = $map !== NULL ? $map : TRUE;
}

/**
 * Implements hook_tmgmt_source_suggestions().
 */
function tmgmt_test_tmgmt_source_suggestions(array $items, Job $job) {
  $suggestions = array();
  foreach ($items as $item) {
    if ($item->plugin == 'test_source') {
      $suggestions[] = array(
        'job_item' => tmgmt_job_item_create('test_source', $item->item_type .  '_suggestion', $item->item_id),
        'reason' => t('Test suggestion for @type source @id', array('@type' => $item->item_type,'@id' => $item->item_id)),
        'from_item' => $item->tjiid,
      );
    }
  }
  return $suggestions;
}
