<?php

/**
 * @file
 * Module file of the translation management test module.
 */

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_test_tmgmt_translator_plugin_info() {
  return array(
    'test_translator' => array(
      'label' => t('Test translator'),
      'description' => t('Simple translator for testing purposes.'),
      'controller class' => 'TMGMTTestTranslatorPluginController',
      'flatten' => TRUE,
      'settings' => array(),
    ),
  );
}

/**
 * Implements hook_tmgmt_source_plugin_info().
 */
function tmgmt_test_tmgmt_source_plugin_info() {
  return array(
    'test_source' => array(
      'label' => t('Test source'),
      'description' => t('Simple source for testing purposes.'),
      'controller class' => 'TMGMTTestSourcePluginController',
    ),
  );
}

function tmgmt_test_trigger_job($target_language = 'de') {
  $job = tmgmt_job_create('en', $target_language);

  for ($i = 1; $i < 3; $i++) {
   $item = tmgmt_job_item_create('test_source', 'test', $i);
   tmgmt_job_add_item($job, $item);
  }

  // Manually specify the translator for now.
  $job->translator = 'test_translator';
  $job->translator_context = array();

  $job->save();
  return $job;
}


