<?php

/**
 * @file
 * Module file of the translation management test module.
 */

/**
 * Implements hook_menu().
 */
function tmgmt_mygengo_menu() {
  $items['admin/config/services/mygengo'] = array(
    'title' => 'myGengo Translator',
    'description' => 'Configure myGengo translation service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tmgmt_mygengo_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'tmgmt_mygengo.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_mygengo_tmgmt_translator_plugin_info() {
  return array(
    'mygengo' => array(
      'label' => t('myGengo translator'),
      'description' => t('A myGengo translator service.'),
      'controller class' => 'TMGMTMyGengoController',
    ),
  );
}

