<?php

/**
 * @file
 * Module file of the translation management test module.
 */

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_mygengo_tmgmt_translator_plugin_info() {
  return array(
    'mygengo' => array(
      'label' => t('myGengo translator'),
      'description' => t('A myGengo translator service.'),
      'controller class' => 'TMGMTMyGengoController',
    ),
  );
}

