<?php

/**
 * @file
 * Please supply a file description.
 */

/**
 * Implementation of hook_tmgmt_translator_plugin_info().
 */
function tmgmt_user_tmgmt_translator_plugin_info() {
  return 'user' => array(
    'label' => t('Local user'),
    'description' => t('Description'),
    'controller class' => 'TMGMTUserTranslatorPluginController',
    'flatten' => TRUE,
    'settings' => array(

    ),
  );
}
