<?php

/**
 * @file
 * UI plugin for the Translation Management system that handles i18n strings.
 */

/**
 * Implements hook_form_FORMID_alter().
 */
function tmgmt_i18n_string_ui_form_i18n_string_translate_page_overview_form_alter(&$form, &$form_state) {
  $form['languages'] = array(
    '#options' => $form['languages']['#rows'],
    '#header' => $form['languages']['#header'],
    '#type' => 'tableselect',
  );
  $form['actions']['#type'] = 'actions';
  $form['actions']['request'] = array(
    '#type' => 'submit',
    '#value' => t('Request translation'),
    '#submit' => array('tmgmt_i18n_string_ui_overview_form_submit'),
    '#validate' => array('tmgmt_i18n_string_ui_overview_form_validate'),
  );
}

/**
 * Validation callback for the i18n String translation overview form.
 */
function tmgmt_i18n_string_ui_overview_form_validate($form, &$form_state) {
  $selected = array_filter($form_state['values']['languages']);
  if (empty($selected)) {
    form_set_error('languages', t('You have to select at least one language for requesting a translation.'));
  }
}

/**
 * Submit callback for the i18n String translation overview form.
 */
function tmgmt_i18n_string_ui_overview_form_submit($form, &$form_state) {
  // @todo Implement this.
}
