<?php

/**
 * @file
 * Source plugin for the Translation Management system that handles nodes.
 */

/**
 * Implements hook_tmgmt_source_plugin_info().
 */
function tmgmt_node_tmgmt_source_plugin_info() {
  return array(
    'node' => array(
      'label' => t('Node'),
      'description' => t('Source handler for nodes.'),
      'controller class' => 'TMGMTNodeSourcePluginController',
    ),
  );
}
