<?php

/**
 * @file
 * Source plugin for the Translation Management system that handles entities.
 */

/**
 * Implements hook_tmgmt_source_plugin_info().
 */
function tmgmt_entity_tmgmt_source_plugin_info() {
  $info['entity'] = array(
    'label' => t('Entity'),
    'description' => t('Source handler for entities.'),
    'plugin controller class' => 'TMGMTEntitySourcePluginController',
    'item types' => array(),
  );
  // @todo Implement item types.
  return $info;
}

/**
 * Updates an entity translation.
 *
 * @param $entity
 *   The entity object (the target).
 * @param $entity_type
 *   The entity type of the source entity.
 * @param $data
 *   An array with the structured translated data.
 * @param $language
 *   The target language.
 *
 * @see TMGMTEntitySourcePluginController::getData()
 */
function tmgmt_entity_update_entity_translation($entity, $entity_type, $data, $language) {
  tmgmt_field_populate_entity($entity, $language, $data);
  entity_save($entity_type, $entity);
}
