<?php

/**
 * @file
 * Main module file for the translation management entity source plugin user
 * interface.
 */

/**
 * @param array $build
 * @param \Drupal\block\BlockPluginInterface $block
 */
function tmgmt_entity_block_view_alter(array &$build, \Drupal\block\BlockPluginInterface $block) {
  if ($block instanceof \Drupal\system\Plugin\Block\SystemMainBlock) {
    if (isset($build['content'][0]['content_translation_overview'])) {
      if (Drupal::entityManager()->getAccessController('tmgmt_job')->createAccess()) {
        module_load_include('inc', 'tmgmt_entity_ui', 'tmgmt_entity_ui.pages');
        $build['content'][0] = drupal_get_form('tmgmt_entity_ui_translate_form', $build['content'][0]);
      }
    }
  }
}

/**
 * Implements tmgmt_entity_tmgmt_source_plugin_info_alter().
 */
function tmgmt_entity_ui_tmgmt_source_plugin_info_alter(&$info) {
  // Alter file and file path info so that tmgmt_entity_ui module is targeted
  // for page callback.
  $info['entity']['file'] = 'tmgmt_entity_ui.pages.inc';
  $info['entity']['file path'] = drupal_get_path('module', 'tmgmt_entity_ui');
}

