<?php
// $Id$

/**
 * @file
 *
 * Provides functions for translation provider nativy.com.
 */


/*
 * Implements hook_menu().
 */
function tmgmt_nativy_menu() {

  /* Remove this path after finishing development! */
  $items['soaptest'] = array(
    'title' => 'Testcallback',
    'type' => MENU_CALLBACK,
    'page callback' => 'tmgmt_nativy_test_page',
    'access arguments' => array('access content'),
  );

  $items['admin/config/services/nativy'] = array(
    'title' => 'Nativy Translator',
    'description' => 'Configure Nativy Translator service.',
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tmgmt_nativy_settings'),
    'access arguments' => array('administer site configuration'),
  );
  
  // @todo menu callback for order complete callback
  $items['nativy/notification'] = array(
    'title' => 'Nativy Notification',
    'description' => 'Callback for the completion notification of a translation job.',
    'type' => MENU_CALLBACK,
    'page callback' => 'tmgmt_nativy_process_translation_result',
    // @todo add a tmgmt permission: 'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_nativy_tmgmt_translator_plugin_info() {
  return array(
    'nativy' => array(
      'label' => t('Nativy translator'),
      'description' => t('Nativy translator plugin that returns translations from nativy.com.'),
      'controller class' => 'TMGMTNativyTranslatorController',
    ),
  );
}

/**
 * Form callback used to configure nativy.com translation service.
 */
function tmgmt_nativy_settings() {

  $form['tmgmt_nativy_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Nativy.com username'),
    '#default_value' => variable_get('tmgmt_nativy_username'),
    '#description' => t('Please enter your username for your account on nativy.com.'),
  );

  $form['tmgmt_nativy_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Nativy.com password'),
    '#default_value' => variable_get('tmgmt_nativy_password'),
    '#description' => t('Please enter your password for your account on nativy.com.'),
  );

  return system_settings_form($form);
}

/*
 * Used for development purposes only!
 */
function tmgmt_nativy_test_page() {

  $xml = '<?xml version="1.0" encoding="utf-8"?>
  <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header>
      <SecuredWebServiceHeader xmlns="https://www.nativy.com/nis">
        <Username>demonis@nativy.com</Username>
        <Password>A9!x57M</Password>
      </SecuredWebServiceHeader>
    </soap:Header>
    <soap:Body>
      <AuthenticateUser xmlns="https://www.nativy.com/nis" />
    </soap:Body>
  </soap:Envelope>';

  $options = array(
    'method' => 'POST',
    'data' => $xml,
    'headers' => array(
      'Content-Type' => 'text/xml; charset=utf-8',
      'Content-Length' => strlen($xml),
      'SoapAction' => 'https://www.nativy.com/nis/AuthenticateUser',
    ),
  );

  dpm(drupal_http_request('http://test.nativy.com/nis/nis.asmx', $options), 'auth');
  
  $response = drupal_http_request('http://test.nativy.com/nis/nis.asmx', $options);
  $doc = simplexml_load_string($response->data);
  $soap = $doc->children('http://schemas.xmlsoap.org/soap/envelope/');
  $nis = $soap->Body[0]->children("https://www.nativy.com/nis");
  $token = (string) $nis->AuthenticateUserResponse[0]->AuthenticateUserResult;
  
  // @todo: Ask Anton how to trigger the non iframe service variant
  
  $xml = '<?xml version="1.0" encoding="utf-8"?>
          <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
            <soap:Header>
              <SecuredWebServiceHeader xmlns="https://www.nativy.com/nis">
                <Username>demonis@nativy.com</Username>
                <Password>A9!x57M</Password>
                <AuthenticatedToken>' . $token . '</AuthenticatedToken>
              </SecuredWebServiceHeader>
            </soap:Header>
            <soap:Body>
              <CreateOffer xmlns="https://www.nativy.com/nis">
                <requ>
                	<offerrequest xmlns="http://www.nativy.com/nis">
              				<settings>
              					<emailCallbackLink>
              						https://www.yourapplication.com/nisinterface/gettranslation
              					</emailCallbackLink>
              					<httpCallbackLink>
												  https://www.yourapplication.com/nativy/notification
  											</httpCallbackLink>
              				</settings>
                			<customer customerId="mailto:demo@nativy.com">
                				<customerEmail>demo@nativy.com</customerEmail>
                				<customerFirstName>Demofirstname</customerFirstName>
                				<customerLastName>Demolastname</customerLastName>
                			</customer>
                			<languages primaryLangCode="de-DE">
                				<language langCode="ms" />
                				<language langCode="jv" />
                				<language langCode="en" />
                				<language langCode="es" />
                			</languages>
                			<textblocks>
                				<textblock code="faq_question1" label="Wie funktioniert nativy?">
                					<description langCode="de-DE">
                						nativy hat ein System entwickelt, um den/die ideale ÜbersetzerIn für jeden
                            Auftrag zu finden. KundInnen können dabei ihre individuellen Kriterien in der Suche
                            nach dem/der idealen ÜbersetzerIn einbringen. nativy übernimmt in dem gesamten Prozess
                            die wichtigsten administrativen Aufgaben, um seinen NutzerInnen das Leben etwas zu
                            erleichtern und die Zusammenarbeit zu beschleunigen. nativy verrechnet seinen
                            KundInnen das von dem/der ÜbersetzerIn festgelegte Honorar inklusive eines
                            geringfügigen Vermittlungsaufschlags.
                					</description>
                					<category>
                						Don\'t know what the heck this element is used for, and it\s not even mentioned in the documentation?!
                					</category>
                				</textblock>
                		</textblocks>
            			</offerrequest>
          		  </requ>
              </CreateOffer>
            </soap:Body>
          </soap:Envelope>';
  
  $options = array(
    'method' => 'POST',
    'data' => $xml,
    'headers' => array(
      'Content-Type' => 'text/xml; charset=utf-8',
      'Content-Length' => strlen($xml),
      'SoapAction' => 'https://www.nativy.com/nis/CreateOffer',
    ),
  );
  
  dpm(drupal_http_request('http://test.nativy.com/nis/nis.asmx', $options), 'createoffer');

  return 'TESTPAGE';
}
