<?php
// $Id$

/**
 * @file
 *
 * Provides functions for translation provider nativy.com.
 */


/*
 * Implements hook_menu().
 */
function tmgmt_nativy_menu() {

  /* Remove this path after finishing development! */
  $items['soaptest'] = array(
    'title' => 'Testcallback',
    'type' => MENU_CALLBACK,
    'page callback' => 'tmgmt_nativy_test_page',
    'access arguments' => array('access content'),
  );

  $items['admin/config/services/nativy'] = array(
    'title' => 'Nativy Translator',
    'description' => 'Configure Nativy Translator service.',
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tmgmt_nativy_settings'),
    'access arguments' => array('administer site configuration'),
  );
  
  // @todo menu callback for order complete callback
  $items['nativy/notification'] = array(
    'title' => 'Nativy Notification',
    'description' => 'Callback for the completion notification of a translation job.',
    'type' => MENU_CALLBACK,
    'page callback' => 'tmgmt_nativy_process_translation_result',
    // @todo add a tmgmt permission: 'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_nativy_tmgmt_translator_plugin_info() {
  return array(
    'nativy' => array(
      'label' => t('Nativy translator'),
      'description' => t('Nativy translator plugin that returns translations from nativy.com.'),
      'controller class' => 'TMGMTNativyTranslatorController',
    ),
  );
}

/**
 * Form callback used to configure nativy.com translation service.
 */
function tmgmt_nativy_settings() {

  $form['tmgmt_nativy_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Nativy.com username'),
    '#default_value' => variable_get('tmgmt_nativy_username'),
    '#description' => t('Please enter your username for your account on nativy.com.'),
  );

  $form['tmgmt_nativy_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Nativy.com password'),
    '#default_value' => variable_get('tmgmt_nativy_password'),
    '#description' => t('Please enter your password for your account on nativy.com.'),
  );

  return system_settings_form($form);
}

/*
 * Used for development purposes only!
 */
function tmgmt_nativy_test_page($jobid) {
  $job = tmgmt_job_load($jobid);
  $translator_name = 'nativy_test';
  $translator = tmgmt_translator_load($translator_name);
  $controller = $translator->getPluginController();
  $form = $form_state = array();
  $job->translator = $translator_name; 
  $form = $controller->jobSettingsForm($form, $form_state, $job);
  return $form;
  return "TESTPAGE Job Id = $jobid";
}
