<?php

/**
 * @file
 * Main module file for the translation management node source plugin user
 * interface.
 */

/**
 * Implements hook_menu().
 */
function tmgmt_node_ui_menu() {
  $items['node/%node/tmgmt'] = array(
    'title' => t('Translation management'),
    'page callback' => 'tmgmt_node_ui_translation_overview',
    'page arguments' => array(1),
    'access callback' => '_translation_tab_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20
  );
  $items['node/%node/tmgmt/create-job'] = array(
    'title' => t('Create a Job'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tmgmt_node_ui_translator_settings_form', 1),
    'access callback' => '_translation_tab_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function tmgmt_node_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'tmgmt_node_ui') . '/views',
  );
}

/**
 * Job overview, which contains the selected item
 */
function tmgmt_node_ui_translation_overview($node) {
  if (!$output = views_embed_view('job_items_current_node', 'default', $node->tnid)) {
    $output = t('There are currently no job items attached to this node.');
  }
  return $output;
}

/**
 * The Node translator settings form.
 */
function tmgmt_node_ui_translator_settings_form($form, &$form_state, $node) {
  // Get all available languages from core translation module.
  $available_languages = entity_metadata_language_list();
  // Pull the label of the node language.
  $node_language = $available_languages[$node->language];
  // Remove LANGUAGE_NONE and the source language from the list of available
  // languages.
  unset($available_languages[LANGUAGE_NONE], $available_languages[$node->language]);
  // Get the translator plugin that is currently selected.
  $translator_plugins = tmgmt_translator_plugin_labels(TRUE);
  $translator_plugins_keyed = array_keys($translator_plugins);
  $selected_translator_plugin = isset($form_state['values']['translation_service']) ? $form_state['values']['translation_service'] : reset($translator_plugins_keyed);
  // Load the plugin info for the selected translator plugin.
  $info = tmgmt_translator_plugin_info($selected_translator_plugin);
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $node->nid,
  );
  $form['source_language'] = array(
    '#type' => 'hidden',
    '#value' => $node->language,
  );
  $form['source_language_display'] = array(
    '#type' => 'item',
    '#title' => t('Source language'),
    '#markup' => $node_language,
  );
  $form['target_language'] = array(
    '#type' => 'select',
    '#title' => t('Target language'),
    '#description' => t('The target language'),
    '#options' => $available_languages,
  );
  $form['translator'] = array(
    '#type' => 'select',
    '#title' => t('Translation type'),
    '#options' => $translator_plugins,
    '#default_value' => $selected_translator_plugin,
    '#ajax' => array(
      'callback' => 'tmgmt_node_ui_get_translator_options',
      'wrapper' => 'tmgmt-translator-options',
      'method' => 'replace',
    ),
  );
  $form['options'] = array(
    '#type' => 'container',
    '#prefix' => '<div id="tmgmt-translator-options">',
    '#suffix' => '</div>',
  );
  $form['options']['description'] = array(
    '#type' => 'item',
    '#title' => t('About this service'),
    '#markup' => $info['description'],
  );
  $form['actions']['#type'] = 'actions';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#weight' => 50,
  );
  return $form;
}

/**
 * Ajax callback to fetch the options provided by a translator.
 */
function tmgmt_node_ui_get_translator_options($form, &$form_state) {
  return $form['options'];
}

/**
 * node translator submit function.
 * will create a job with the node as item.
 */
function tmgmt_node_ui_translator_settings_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  // Create the job object.
  $job = tmgmt_job_create($values['source_language'], $values['target_language'], array('translator' => $values['translator']));
  // Create a job item and add it to the job.
  $job->addItem(tmgmt_job_item_create('node', 'node', $values['nid']));
  $job->prepared('Job has been prepared.');
  $job->save();
  // Print a message to the screen and redirect the user.
  drupal_set_message(t('Translation job has been created.'));
  $form_state['redirect'] = 'node/' . $values['nid'] . '/tmgmt';
}
