<?php
/**
 * @file
 * Common Translation managment UI.
 */

/**
 * Implements hook_permission().
 */
function tmgmt_ui_permission() {
  return array(
    'administer tmgmt ui' => array(
      'title' => t('Administer Translation Management UI'),
    ),
    'access tmgmt ui' => array(
      'title' => t('Access Translation Management UI'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function tmgmt_ui_menu() {
  $items['admin/config/regional/tmgmt/tmgmt_ui'] = array(
    'title' => 'UI',
    'description' => 'Administer Translation Management UI',
    'page callback' => 'tmgmt_ui_fake_admin',
    'access arguments' => array('administer tmgmt ui'),
    'weight' => -1,
    'file' => 'tmgmt_ui.pages.inc',
  );
  $items['admin/tmgmt'] = array(
    'title' => 'Translation Management',
    'description' => 'Use the Translation Management',
    'page callback' => 'tmgmt_ui_content',
    'access arguments' => array('access tmgmt ui'),
    'weight' => -20,
    'file' => 'tmgmt_ui.pages.inc',
  );
  $items['admin/tmgmt/my-translation-management'] = array(
    'title' => 'Overview',
    'page callback' => 'tmgmt_ui_content',
    'access arguments' => array('access tmgmt ui'),
    'weight' => -20,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'tmgmt_ui.pages.inc',
  );
  $items['admin/tmgmt/jobs/%tmgmt_job'] = array(
    'title' => 'Job',
    'page callback' => 'tmgmt_job_view',
    'page arguments' => array(3),
    'access arguments' => array('administer tmgmt'),
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'tmgmt_ui.pages.inc',
  );
  $items['tmgmt/checkout/%tmgmt_ui_job_multiple'] = array(
    'title' => 'Job checkout form',
    'page callback' => 'tmgmt_ui_checkout_wizard',
    'page arguments' => array(2),
    'access arguments' => array('access tmgmt ui'),
    'file' => 'tmgmt_ui.pages.inc',
  );

  // Add source overview pages.
  foreach (tmgmt_source_plugin_info() as $plugin_type => $info) {
    $plugin = tmgmt_source_plugin_controller($plugin_type);
    $items = array_merge($items, $plugin->hook_menu());
  }
  return $items;
}

/**
 * Load callback to load multiple jobs.
 *
 * @todo: This function can be easily tested.
 */
function tmgmt_ui_job_multiple_load($job_ids) {
  $job_ids = explode(',', $job_ids);
  $jobs = tmgmt_job_load_multiple($job_ids);
  return $jobs;
}

/**
 * Implements hook_views_api().
 */
function tmgmt_ui_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_views_default_views().
 */
function tmgmt_ui_views_default_views() {
  return _tmgmt_ui_load_all_exports('tmgmt_ui', 'views', 'view.inc', 'view');
}

/**
 * Fetches an array of exportables from files.
 *
 * @param $module
 *   The module invoking this request. (Can be called by other modules.)
 * @param $directory
 *   The subdirectory in the custom module.
 * @param $extension
 *   The file extension.
 * @param $name
 *   The name of the variable found in each file. Defaults to the same as
 *   $extension.
 *
 * @return array
 *   Array of $name objects.
 */
function _tmgmt_ui_load_all_exports($module, $directory, $extension, $name = NULL) {
  if (!$name) {
    $name = $extension;
  }
  $return = array();
  // Find all the files in the directory with the correct extension.
  $files = file_scan_directory(drupal_get_path('module', $module) . "/$directory", "/\.{$extension}$/");
  foreach ($files as $path => $file) {
    require $path;
    if (isset($name)) {
      $return[$name->name] = $name;
    }
  }
  return $return;
}
