<?php

/**
 * @file
 * Main module file for the translation management node source plugin user
 * interface.
 */

/**
 * Implements hook_page_alter().
 */
function tmgmt_node_ui_page_alter(&$page) {
  // Translation tabs for nodes.
  if ($node = menu_get_object()) {
    if (isset($page['content']['system_main']['translation_node_overview']) && entity_access('create', 'tmgmt_job')) {
      module_load_include('inc', 'tmgmt_node_ui', 'tmgmt_node_ui.pages');
      $page['content']['system_main']['translation_node_overview'] = drupal_get_form('tmgmt_node_ui_node_form', $node, $page['content']['system_main']['translation_node_overview']);
    }
  }
}
