<?php

/**
 * @file
 * Main module file for the translation management node source plugin user
 * interface.
 */

/**
 * Implements hook_menu().
 */
function tmgmt_node_ui_menu() {
  $items['node/%node/translate/overview'] = array(
    'title' => 'Translation jobs',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 10
  );
  $items['node/%node/translate/view'] = array(
    'title' => 'Job History',
    'page callback' => 'tmgmt_node_ui_translation_overview',
    'page arguments' => array(1),
    'access callback' => '_translation_tab_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20
  );
  return $items;
}

/*
 * Ebeds the view.
 */
function tmgmt_node_ui_translation_overview() {
  return views_embed_view('job_items_current_node');
}

/**
 * Implements hook_views_api().
 */
function tmgmt_node_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'tmgmt_node_ui') . '/views',
  );
}
